name: Mutants

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mutants:
    uses: mozilla/actions/.github/workflows/mutants.yml@bf3fb2950385cdbf80d0248db988d39096963755 # v2.0.0
