name: Mutants

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mutants:
    uses: mozilla/actions/.github/workflows/mutants.yml@32d84c77ea1bb513afbd253f94f67ae138b7d8be # v2.0.10
