name: Mutants

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mutants:
    uses: mozilla/actions/.github/workflows/mutants.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6
