name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: mozilla/actions/rust@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6
        with:
          components: llvm-tools
          tools: cargo-llvm-cov
          token: ${{ github.token }}
      - name: Run tests and determine coverage
        run: cargo llvm-cov test --codecov --output-path codecov.json
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: codecov.json
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }} # zizmor: ignore[secrets-outside-env]
          verbose: true
          flags: linux
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # zizmor: ignore[secrets-outside-env]

  rustfmt:
    uses: mozilla/actions/.github/workflows/rustfmt.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6

  clippy:
    uses: mozilla/actions/.github/workflows/clippy.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6

  deny:
    uses: mozilla/actions/.github/workflows/deny.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6

  machete:
    uses: mozilla/actions/.github/workflows/machete.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6

  semver:
    name: Check semver
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: mozilla/actions/semver@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6

  mutants-pr:
    if: github.event_name == 'pull_request'
    uses: mozilla/actions/.github/workflows/mutants-pr.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6

  dependency-review:
    if: github.event_name == 'pull_request'
    uses: mozilla/actions/.github/workflows/dependency-review.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6

  actionlint:
    uses: mozilla/actions/.github/workflows/actionlint.yml@f8e0d5c4cff5006ee24b6356272d47c9911450d1 # v2.0.6
    permissions:
      contents: read
      security-events: write # Required to upload SARIF results to GitHub
